# saving path
save_path: ./saved_models/cifar10_n1500_l100_long_s0
save_model: True
overwrite: False

# training configuration
num_train_iter: 16000
num_eval_iter: 1600
max_labeled_per_class: 1500
max_unlabeled_per_class: 3000
num_val_per_class: 5
batch_size: 64
eval_batch_size: 1024
ema_m: 0.999
use_mixup_drw: True
drw_warm: 0.75

# optimizer configurations
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.0005
amp: False

# backbone net configurations
net: WideResNet
net_from_name: False
depth: 28
widen_factor: 2
leaky_slope: 0.1
dropout: 0.0

# data configurations
data_dir: ./data
dataset: cifar10
train_sampler: RandomSampler
num_classes: 10
num_workers: 1
seed: 0
gpu: 0

# imbalanced settings
lb_imb_ratio: 100
ulb_imb_ratio: 0.01
imb_type: long

# label shift estimation
lse_algs: [BBSE, RLLS, MLLS]
calibrations: [None, BCTS]
num_ensemble: 10
